### ISSUE TITLE
Epic: New Navigation Integration

### ISSUE THREAD

**Issue by bignamehere** [USDA-FPAC/fpac-design-system#9]
Breaking out my review brand of the current state of development and making a list of TODOs

**General/Global Component Updates:**

- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #21

**Style-Based Updates**:

- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27
- [x] #28

**Advanced Updates:**

- [x] #29
- [x] #30

**Comment by bignamehere** [comment]
Unselected #29 as it needs to be looked at for proper routing, and event bubbling.

**Comment by jamierthompson** [comment]
Unselected all to start new branch for issue/9

**Comment by bignamehere** [comment]
Epic is closed and rolled into Main (a978fd2fdfbe7f139c45de90f0cb260b303c94cd)
